#!/bin/bash
# Some functions as a wrapper around ansible in docker

# We like colors
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
yellow=`tput setaf 3`

# Here the aliases
alias ansible-playbook='docker run --privileged=true -it --rm --name ansible-docker quay.io/tiramisu/mr.ansible ansible-playbook'
